config = {'version': 'v1',
          'config': {'visState': {'filters': [],
                                  'layers': [{'id': '72546h',
                                              'type': 'geojson',
                                              'config': {'dataId': 'unnamed',
                                                         'label': 'ri_dt',
                                                         'color': [30, 150, 190],
                                                         'columns': {'geojson': '_geojson'},
                                                         'isVisible': True,
                                                         'visConfig': {'opacity': 0.8,
                                                                       'thickness': 0.5,
                                                                       'strokeColor': [137, 218, 193],
                                                                       'colorRange': {'name': 'Global Warming',
                                                                                      'type': 'sequential',
                                                                                      'category': 'Uber',
                                                                                      'colors': ['#5A1846',
                                                                                                 '#900C3F',
                                                                                                 '#C70039',
                                                                                                 '#E3611C',
                                                                                                 '#F1920E',
                                                                                                 '#FFC300']},
                                                                       'strokeColorRange': {'name': 'Global Warming',
                                                                                            'type': 'sequential',
                                                                                            'category': 'Uber',
                                                                                            'colors': ['#5A1846',
                                                                                                       '#900C3F',
                                                                                                       '#C70039',
                                                                                                       '#E3611C',
                                                                                                       '#F1920E',
                                                                                                       '#FFC300']},
                                                                       'radius': 10,
                                                                       'sizeRange': [0, 10],
                                                                       'radiusRange': [0, 50],
                                                                       'heightRange': [0, 500],
                                                                       'elevationScale': 0.3,
                                                                       'stroked': True,
                                                                       'filled': True,
                                                                       'enable3d': True,
                                                                       'wireframe': False},
                                                         'textLabel': [{'field': None,
                                                                        'color': [255, 255, 255],
                                                                        'size': 18,
                                                                        'offset': [0, 0],
                                                                        'anchor': 'start',
                                                                        'alignment': 'center'}]},
                                              'visualChannels': {'colorField': {'name': 'Bldg Proje', 'type': 'string'},
                                                                 'colorScale': 'ordinal',
                                                                 'strokeColorField': None,
                                                                 'strokeColorScale': 'quantile',
                                                                 'sizeField': None,
                                                                 'sizeScale': 'linear',
                                                                 'heightField': {'name': 'heightroof', 'type': 'real'},
                                                                 'heightScale': 'linear',
                                                                 'radiusField': None,
                                                                 'radiusScale': 'linear'}}],
                                  'interactionConfig': {'tooltip': {'fieldsToShow': {'unnamed': ['fid',
                                                                                                 'Bldg Proje',
                                                                                                 'cnstrct_yr',
                                                                                                 'feat_code',
                                                                                                 'groundelev']},
                                                                    'enabled': True},
                                                        'brush': {'size': 0.5, 'enabled': False}},
                                  'layerBlending': 'normal',
                                  'splitMaps': [],
                                  'animationConfig': {'currentTime': None, 'speed': 1}},
                     'mapState': {'bearing': 24,
                                  'dragRotate': True,
                                  'latitude': 40.762657188357366,
                                  'longitude': -73.94932417862506,
                                  'pitch': 50,
                                  'zoom': 15,
                                  'isSplit': False},
                     'mapStyle': {'styleType': 'dark',
                                  'topLayerGroups': {},
                                  'visibleLayerGroups': {'label': True,
                                                         'road': True,
                                                         'border': False,
                                                         'building': True,
                                                         'water': True,
                                                         'land': True,
                                                         '3d building': False},
                                  'threeDBuildingColor': [9.665468314072013,
                                                          17.18305478057247,
                                                          31.1442867897876],
                                  'mapStyles': {}}}}
